version: "3"

services:
  api:
    container_name: todo-api
    restart: always
    build: ./todo-api
    ports:
      - "3001:3001"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  app:
    container_name: todo-app
    stdin_open: true
    volumes:
      - ./todo-app/src:/usr/src/app/src
      - ./todo-app/public:/usr/src/app/public
    build: ./todo-app
    ports:
      - "3000:3000"
    links:
      - api
